CREATE DATABASE IF NOT EXISTS VENTAS;

USE VENTAS;

CREATE TABLE IF NOT EXISTS NOM_CLIENTE (
    'ID_CLI' INT AUTO_INCREMENT,
    'NOMBRE' VARCHAR(50),
    'RFC' VARCHAR(13),
    'DIRECCION' VARCHAR(50),
    'TELEFONO' VARCHAR(15),
    PRIMARY KEY ('ID_CLI')
);

CREATE TABLE IF NOT EXISTS NOM_VENDEDOR (
    'ID_VEN' INT AUTO_INCREMENT,
    'NOMBRE' VARCHAR(50),
    'DEPARTAMENTO' VARCHAR(50),
    'TELEFONO' VARCHAR(15),
    PRIMARY KEY ('ID_VEN')
);